spring:
  datasource:
    username: checker
    password: 123456
    url: jdbc:postgresql://127.0.0.1:5432/project2
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
